import Logos.Logic.Logic
import Logos.Logic.Judgment
import Logos.Logic.Fun
import Logos.Logic.Prop
import Logos.Logic.Unit
import Logos.Logic.Dual
import Logos.Logic.Quant
import Logos.Logic.Rel
import Logos.Logic.Eq
